version: '3.8'
services:
  postgres:
    container_name: ${KEYCLOAK_POSTGRES_CONTAINER_NAME}
    image: postgres:16.2
    volumes:
      - keycloak_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    networks:
      - brazona-keycloak-network
  keycloak:
    container_name: ${KEYCLOAK_CONTAINER_NAME}
    image: ${KEYCLOAK_IMAGE}
    command: ${KEYCLOAK_COMMAND}
    restart: always
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${KEYCLOAK_POSTGRES_CONTAINER_NAME}/${KEYCLOAK_POSTGRES_DB}
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    ports:
      - "${KEYCLOAK_PORT_EXT}:8080"
    depends_on:
      - postgres
    networks:
      - brazona-keycloak-network
volumes:
  keycloak_pg_data:
    driver: local
networks:
  brazona-keycloak-network:
    driver: bridge